name: 🐛 Bug Report
description: Report an issue that should be fixed
labels:
  - bug
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. It helps make github-code-search better.

        Make sure you are running the [latest](https://github.com/fulll/github-code-search?tab=readme-ov-file#installation) version of github-code-search.
        The bug you are experiencing may already have been fixed.

        Please try to include as much information as possible.

  - type: input
    attributes:
      label: What version of github-code-search is running?
      description: Copy the output of `github-code-search --version`
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a code snippet that can reproduce it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible, please provide text instead of a screenshot.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible, please provide text instead of a screenshot.
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
